# Shows how the r-build-check.yml can be called from another repository.
name: build-check
on:
    pull_request:
        branches:
        - 'devel'
        - 'main'
    workflow_dispatch:
jobs:
    build-check:
        uses: FertigLab/actions/.github/workflows/r-build-check.yml@v1.2.2
