#inspired by https://docs.cirro.bio/pipelines/development/#automated-testing
name: test

on:
  pull_request:
      branches:
      - 'main'
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.2.1

      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: install nextflow
        run: |
          cd ..
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/

      - name: stub run
        run: 
          nextflow run spacemarkers/nextflow/main.nf \
          --input spacemarkers/nextflow/samplesheet.csv \
          -c spacemarkers/nextflow/nextflow.config \
          -stub -profile test --max_cpus 1 --max_memory '8GB'